### ISSUE TITLE
ExerciseManager

### ISSUE THREAD

**Issue by Thaxillias** [scorupco/android-projekt-trener#1]
Utworzenie singletona dla zarządzania ćwiczeniami. Do jego zadań należy:

- [x]  przechowywanie definicji wszystkich ćwiczeń w aplikacji
- [x] zapis/odczyt definicji ćwiczeń na/z urządzenia
- [x] dostarczanie listy ćwiczeń do kontrolek (np. do adaptera w celu ich wyświetlenia)
- [x] dodawanie/modyfikowanie/usuwanie ćwiczeń

Przed bezpiecznym usunięciem ćwiczenia należy sprawdzić, czy istnieje plan wykorzystujący to ćwiczenie, jeżeli tak to uniemożliwić usunięcie.

**Comment by scorupco** [comment]
TODO: Przed bezpiecznym usunięciem ćwiczenia należy sprawdzić, czy istnieje plan wykorzystujący to ćwiczenie, jeżeli tak to uniemożliwić usunięcie.
