### ISSUE TITLE
Dodawanie i edytowanie cwiczen

### ISSUE THREAD

**Issue by scorupco** [scorupco/android-projekt-trener#10]
Kto ruszal moj kod bez informowania mnie o tym?
Dodawanie, edytowanie i kasowanie cwiczen nie dziala na obecnym ekranie. Trzeba sie wrocic i wejsc jeszcze raz by zadzialalo.Wrrrrrrrrrrrrr................
Jak ja mam odpowiadać za tą część jak ktoś to ruszał bez mojej wiedzy?

**Comment by mily94** [comment]
Sorry, nie przyznam się do ruszania tego kodu :p
7 cze 2016 23:58 "scorupco" <notifications@github.com> napisał(a):

**Comment by Thaxillias** [comment]
Ja zmieniałem, bo po zmianie na singleton w ogóle przestało
dodawać/edytować i zapisywać. A musiałem mu na spotkaniu pokazać, że to
działa.
08.06.2016 00:02 "mily94" <notifications@github.com> napisał(a):

**Comment by scorupco** [comment]
Dalej to nie dziala. Ja ma to naprawic czy ty to zrobisz? A co bylo nie tak z poprzednim singletonem?

**Comment by Thaxillias** [comment]
Rzucał ciągle null pointerem podczas pobierania kontekstu aplikacji.
08.06.2016 00:12 "scorupco" <notifications@github.com> napisał(a):

**Comment by scorupco** [comment]
Testowalam to na telefonie z androidem i dzialalo. Poprawie to, ale juz nie ruszajcie mojego kodu. A nastepym razem jak juz bedzie trzeba cos poprawic to powiedzcie (zalozcie tutaj buga), a nie dowiaduje sie teraz. ps. odpisal ci prowadzacy czy nie?

**Comment by scorupco** [comment]
Spinamy dupe do piatku, zeby to idealnie dzialalo. I probujemy to oddac, ok?

**Comment by Thaxillias** [comment]
Jeszcze nie.
08.06.2016 00:24 "scorupco" <notifications@github.com> napisał(a):
