### ISSUE TITLE
Zmiana backgroundu

### ISSUE THREAD

**Issue by scorupco** [scorupco/android-projekt-trener#11]
Nie działa zmiana tła

**Comment by mily94** [comment]
Wiem. Pod tą listą nic się nie kryje. Nie miałem pomysłu jak by to zrobić i
czy w ogóle to jest potrzebne. Zmiana tła na obrazek sprawi, że aplikacja
będzie nieczytelna
8 cze 2016 09:51 "scorupco" <notifications@github.com> napisał(a):

**Comment by Thaxillias** [comment]
Co najwyżej można spróbować ustawić inne kolory(motywy) np. czarne tło
białe napisy | białe tło czarne napisy.

2016-06-08 9:56 GMT+02:00 mily94 <notifications@github.com>:

**Comment by scorupco** [comment]
Zamykam temat. 
Po rozmowie z Miłoszem rezygnujemy ze zmieniania backgroundu.
