### ISSUE TITLE
Dokumentacja w latex

### ISSUE THREAD

**Issue by scorupco** [scorupco/android-projekt-trener#15]
https://www.sharelatex.com/project/575e630025e5238766fe1960

**Comment by scorupco** [comment]
https://www.sharelatex.com/project/575e630025e5238766fe1960

**Comment by scorupco** [comment]
Proszę o opinię i uwagi  na temat dokumentacji.

**Comment by Thaxillias** [comment]
Z tego, co kojarzę co mówił prowadzący o tej dokumentacji to jest OK. Usunąłbym tylko zwrot "drodzy Czytelnicy" ze wstępu. Brzmi trochę za bardzo literacko, jak na dokumentację.
