### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Thaxillias** [scorupco/android-projekt-trener#3]
Timer odliczający czas rundy.
Oczekiwane funkcjonalność:
- [x] odtworzenie sygnału dźwiękowego 
- [x] odliczanie czasu rundy
- [x] odtworzenie sygnału początku sprintu
- [x] odtworzenie sygnału końca sprintu
- [x] odtworzenie sygnału końca rundy

**Comment by scorupco** [comment]
co z tym issue?

**Comment by scorupco** [comment]
leci lista ćwiczeń  z managera ćwieczeń, a nie plan
