### ISSUE TITLE
Ekran Tworzenia/Edycji Planu Treningowego

### ISSUE THREAD

**Issue by Thaxillias** [scorupco/android-projekt-trener#7]
Activity do edycji parametrów planu treningowego. Umożliwia dodawanie ćwiczeń na podstawie istniejących definicji (np. z dropdowna), oraz ustawienie takich właściwości, jak przerwa między ćwiczeniami.
Możliwość ustawienia harmonogramu planu (np. poniedziałki o 18:00).

**Comment by Thaxillias** [comment]
Zrobione.

**Comment by scorupco** [comment]
Nie zrobione. Edytowanie pierwszego planu na liscie stwarza nowy plan.

**Comment by Thaxillias** [comment]
Poprawiono.
