### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Thaxillias** [scorupco/android-projekt-trener#8]
Singleton przechowujący ustawienia aplikacji, takie jak domyślne wartości parametrów, sygnałów dźwiękowych itp.

Powinny być zapisywane na pamięci urządzenia.

**Comment by scorupco** [comment]
Możesz dorobić w liście tych dźwięków znaczek checked, który mówi który dźwiek wybraliśmy?

**Comment by mily94** [comment]
Mogę, ale...
Dobrze zrobię
