### ISSUE TITLE
Muszę kilnąć apkę, żeby muzyka przestała grać

### ISSUE THREAD

**Issue by scorupco** [scorupco/android-projekt-trener#9]
Na stronie settings'ów fajnie by było, gdyby muzyka przestala grać na cofnięcie do głownego menu. A muzyka wybrana, żeby otworzyła się przy "run plan"

**Comment by scorupco** [comment]
Dodaj "Eye of the tiger" - jak w filmie Rocky Balboa :)

**Comment by mily94** [comment]
Może i masz rację, ale z tego co się domyślałem to muzyka tutaj to miał być
krótki sygnał dźwiękowy, więc zdążyłby się skończyć przed cofnięciem do
głównego menu. Po prostu te pliki miałem pod ręką i wstawiłem :p W mojej
wizji te dźwięki to miały być pikacze, które uruchamiałyby się podczs
sprintu w ćwiczeniu (na końcu ćwiczenia)
7 cze 2016 23:48 "scorupco" <notifications@github.com> napisał(a):
